config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'carts/index'
  get 'order' => 'admin_users#show', as: :in_order
  get 'order_end' => 'admin_users#show2', as: :order_end
  get 'order_cancel' => 'admin_users#show3', as: :order_cancel


devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  # devise_for :admins
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  get "/users/show" => "users#show",as: :users
  delete "/users/destroy" =>"users#destroy"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy]
  resources :carts
  resources :admin_users, only:[:index,:show,:destroy,:update]
  resources :orders, only: [:create,:new,:index,:update]
  resources :categories,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :brands,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :sizes,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :colors,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :contacts, only: [:index, :new, :create, :destroy]

  get "/admin_users/edit/:id" => "admin_users#edit", as: :edit_adminusers_to_users
  post "/admin_users/:id" => "admin_users#update", as: :adminusers_to_users
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :items
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name,:kana_name,:email,:phone, :message,presence: true,length: {maximum:1000}
end

app/models/detail.rb
class Detail < ApplicationRecord

	belongs_to :user
	belongs_to :item
	belongs_to :order

	enum active:{preparation: 0, shipment: 1}
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	attachment :image2
	attachment :image3
	attachment :image4
	attachment :image5
	has_many :histories
	has_many :carts
	belongs_to :category
	belongs_to :brand
	belongs_to :color
	belongs_to :size


	enum active: { display: 0, hide: 1}

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :details
	belongs_to :user

	enum order_status: { in_ordered: 0, preparation: 1, in_delivery: 2, finish: 3, cancel: 4}
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :lastname, :firstname, :postal_code, :address, :phone,:phone2,:phone3, presence: true
  validates :kana_lastname, :kana_firstname,  presence: true,
  			 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "は全角カタカナで入力して下さい"
                 }

  enum active: { active: 0, inactive: 1 }
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index #カート内の書品一覧
		@carts = Cart.all
		@fee = 360 #送料
		@total_price = 0
		@carts.each do |cart|
	      if current_user.id == cart.user_id
	         @total_price += cart.item.price*cart.count
	      end
    	end
    	@random = Item.order("RANDOM()").first
	end

	def create
		@cart = Cart.new(cart_params)
		@cart.user_id = current_user.id
		if Cart.find_by(item_id: @cart.item_id,user_id:current_user.id)
       		redirect_to carts_path, flash: {n: "選んだ商品は既にカートに入っています。ご確認ください。"}
    	else
			@cart.save
			redirect_to carts_path
		end
	end

	def update
		@cart = Cart.find(params[:id])
		@cart.update(cart_params)
		redirect_to carts_path
	end

	def destroy
		@cart = Cart.find(params[:id])
		@cart.delete
		redirect_to carts_path
	end


	private

	def cart_params
		params.require(:cart).permit(:user_id,:item_id,:count)
	end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/carts/index.html.erb
<br><br><br>
<div class="view">
<% if admin_signed_in? %>
  <%=link_to("カテゴリー編集",categories_path)%>
<% end %>

    <% if params[:q].present? && params[:q][:item_name_cont].present? %>
      <p>検索語句：　<%= params[:q][:item_name_or_label_name_or_item_name_cont] %></p>
    <% end %>
        <table class="item_index_box">
        <% if @carts.where(user_id:current_user.id).presence == nil %>
        </table>
         <font color="gray"><h2>現在、カートには何も入っていません。</h2></font>

        
          <%= link_to items_path do %>
        <div class="btn2">商品一覧へ</div>
        <% end %>
    <% else %>
      <% @carts.each do |cart| %>
          <!--画像画面左　登録がない場合noimageを表示-->
          <td>
          <div class="border"></div>
            <% if current_user.id == cart.user_id %>
            <div class="item-image">
            <%= attachment_image_tag cart.item, :image, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %>
            <% end %>
          </td>
          <!--商品内容-->
          <td class="item_index_box_detail">
          <p><h2><%= link_to "#{cart.item.item_name}", item_path(cart.item) %></h2></p>
          <p class="tag"><%= cart.item.category.name %></p> <p class="tag">サイズ：<%= cart.item.size.size_name %></p>
          <p>カラー:<%= cart.item.color.color_name %></p>
          <p><%= number_to_currency(cart.item.price, :precision => 0) %>
            <% if cart.item.stock == 0 %>
            <span>( 売り切れ )</span>
            <% elsif cart.item.stock <= 5 %>
            <span>( 在庫 : 残りわずか )</span>
            <% elsif cart.item.stock >= 5 && cart.item.stock <= 10 %>
            <span>( 在庫 : △ )</span>
            <% else %>
            <span>( 在庫 : ○ )</span>
            <% end %></p>
                <% if cart.item.active != "display"%>
                <p style="color:red">販売停止中商品です。</p>
                <% end %>
                    <%= form_for(cart, url: cart_path(cart.id), html: {method: 'PUT'}) do |f| %>
                      <!--商品の個数を変更するフォーム-->
                      <%= f.number_field :count ,min:0,max: cart.item.stock %>
                      <%= f.hidden_field :user_id, :value => current_user.id %>
                      <%= f.hidden_field :item_id, :value => cart.item.id %>
                      <%= f.submit "個数を変更" %>
                      <!--商品削除ボタン-->
                      <button><%= link_to "　削除　", cart_path(cart.id), method: :delete %></button><br>
                    <% end %>
                    <div class="border"></div>
                    <!-- １商品の合計金額 -->
                    小計: <%= number_to_currency(cart.item.price*cart.count,  precision:0) %><br>
                  </div></div>
                </td></tr></div>
            </td></tr>
      <% end %></table>

      <% if @total_price <= 2000 %>
        <div class="total-price-box">
        <p>送料：<%= @fee %>円</p>
        <div class="border2">
          <p>カート内合計金額：<%= @total_price+@fee %>円
          <p><font color='red'>送料無料まであと<%= 2000-@total_price %>円！</font></p><br>
      こちらの商品もいかがですか？
          <div class="item-image">
                <%= attachment_image_tag @random, :image, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image2" %>
          </div>
      <%= link_to "#{@random.item_name}", item_path(@random) %><br>
      <%= @random.price %>円


        <% else %>
        <div class="total-price-box">
        <p><font color='red'>送料：無料</font></p>
        <div class="border2">
        <h4>カート内合計金額：<%= number_to_currency(@total_price, precision:0) %></h4><br>
        <% end %></div><br><br>
      <% if @carts.presence != nil %>
          <%= link_to new_order_path do %>
          <div class="square_btn1">レジへ進む</div>
          <% end %>
          <%= link_to items_path do %>
        <div class="square_btn2">買い物を続ける</div>
      <% end %>
      <% end %>
      <% end %>
      <br>
    </div>
  </div>