config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'carts/index'
  get 'order' => 'admin_users#show', as: :in_order
  get 'order_end' => 'admin_users#show2', as: :order_end
  get 'order_cancel' => 'admin_users#show3', as: :order_cancel


devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  # devise_for :admins
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  get "/users/show" => "users#show",as: :users
  delete "/users/destroy" =>"users#destroy"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy]
  resources :carts
  resources :admin_users, only:[:index,:show,:destroy,:update]
  resources :orders, only: [:create,:new,:index,:update]
  resources :categories,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :brands,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :sizes,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :colors,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :contacts, only: [:index, :new, :create, :destroy]

  get "/admin_users/edit/:id" => "admin_users#edit", as: :edit_adminusers_to_users
  post "/admin_users/:id" => "admin_users#update", as: :adminusers_to_users
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :items
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name,:kana_name,:email,:phone, :message,presence: true,length: {maximum:1000}
end

app/models/detail.rb
class Detail < ApplicationRecord

	belongs_to :user
	belongs_to :item
	belongs_to :order

	enum active:{preparation: 0, shipment: 1}
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	attachment :image2
	attachment :image3
	attachment :image4
	attachment :image5
	has_many :histories
	has_many :carts
	belongs_to :category
	belongs_to :brand
	belongs_to :color
	belongs_to :size


	enum active: { display: 0, hide: 1}

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :details
	belongs_to :user

	enum order_status: { in_ordered: 0, preparation: 1, in_delivery: 2, finish: 3, cancel: 4}
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :lastname, :firstname, :postal_code, :address, :phone,:phone2,:phone3, presence: true
  validates :kana_lastname, :kana_firstname,  presence: true,
  			 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "は全角カタカナで入力して下さい"
                 }

  enum active: { active: 0, inactive: 1 }
  has_many :orders
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @item = Item.where(active: 0)
    @q = @item.search(params[:q])
    @items = @q.result(distinct: true)

    #非表示アイテムを表示しない
    @no_item = Item.where(active: 1)
    @no_q = @no_item.search(params[:q])
    @no_items = @no_q.result(distinct: true)
    @sizes = Size.all
    @categories = Category.all
    @brands = Brand.all
  end


  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)
    if @item.save
       redirect_to items_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @cart = Cart.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      #updateが完了したら一覧ページへリダイレクト
      redirect_to ("/items")
    else
      #updateを失敗すると編集ページへ
      render :edit
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.delete
    redirect_to("/items")
  end

  private
    def item_params
        params.require(:item).
        permit(:active,
              :item_name,
              :image,
              :image2,
              :image3,
              :image4,
              :image5,
              :price,
              :item_season,
              :stock,
              :color_id,
              :size_id,
              :category_id,
              :brand_id,
              :color_name,
              :release_date,
              :description)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/items/_form.html.erb
<br>
<br>
<br>
<div class="view">
  <div class="row">
  <h2>商品登録</h2>
  <%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
        <div id="error_explanation">
        <h2><%= @item.errors.count %>件のエラーが発生しました。</h2>
        <ul>
        <% @item.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

      <div class="col-sm-8">
        表示・非表示　　<%= f.select :active, Item.actives_i18n.keys.map { |k| [Item.actives_i18n[k], k]} %>
      </div>

    　<div class="col-sm-8">
        商品画像1　　　<%= f.attachment_field :image %>
      </div>

    　<div class="col-sm-8">
        商品画像2　　　<%= f.attachment_field :image2 %>
      </div>

      <div class="col-sm-8">
        商品名　　　　　<%= f.text_field :item_name, class:"form-control", rows:"3" %>
      </div>
       <div class="col-sm-8">
        ブランド　　　　<%= f.collection_select :brand_id, Brand.all, :id, :brand_name %><%=link_to("編集",brands_path)%><br>
      </div>
       <div class="col-sm-8">
        カラー　<%= f.collection_select :color_id, Color.all, :id, :color_name %><%=link_to("編集",colors_path)%><br>
        サイズ　<%= f.collection_select :size_id, Size.all, :id, :size_name %><%=link_to("編集",sizes_path)%><br>
      </div>
       <div class="col-sm-8">
        カテゴリー　　　<%= f.collection_select :category_id, Category.all, :id, :name %><%=link_to("編集",categories_path)%>
      </div>
      <div class="col-sm-8">
        価格　　　　　　<%= f.text_field :price, class:"form-control", rows:"3" %>
      </div>
      <div class="col-sm-8">
        在庫数　　　　　<%= f.text_field :stock, class:"form-control", rows:"3" %>
      </div>
      <div class="col-sm-8">
        紹介文　　　　　<%= f.text_area :description, class:"form-control", rows:"3" %>
      </div>
      <div class="col-sm-8">
        発売日　　　　　<%= f.date_field :release_date, class:"form-control", rows:"3" %>
      </div>

    <div class="col-sm-8">
    <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
    </div>
     <div class="col-sm-8">
      <br><br>
    <h3><%= link_to"一覧に戻る", "/" %></h3>
    </div>
  </div>
</div>
  <% end %>

app/views/items/edit.html.erb
<h1>edit</h1>
<%= render 'form', item: @item %>

app/views/items/index.html.erb
<div class="view">
<%if flash%>
   　<!-- ログイン時のメッセージ格納 -->
      <% flash.each do |key,msg|%>
      	<br>
      	<br>
       <div class="flash_<%= key%> flash">
         <%= msg %>
       </div>
         <br>
         <br>
      <% end %>
   <% end %>

   		<div class="row">
						<!-- 任意のID指定。クラスとデータ属性の指定。 -->
						<div id="carousel-example" class="carousel slide " data-ride="carousel" data-interval="5000">
						<!-- インジケーターの設置。下部の○●ボタン。 -->
						<ol class="carousel-indicators">
						<li data-target="#carousel-example" data-slide-to="0" class="active"></li>
						<li data-target="#carousel-example" data-slide-to="1"></li>
						<li data-target="#carousel-example" data-slide-to="2"></li>
						</ol>

							<!-- スライドの内容 -->
							<div class="carousel-inner">
									<div class="item active">
										<%= image_tag "dax.jpg", :width=>'100%' %>
									</div>
									<div class="item">
										<%= image_tag "dax2.jpg", :width=>'100%' %>
									</div>
									<div class="item">
										<%= image_tag "poodle.jpg", :width=>'100%' %>
									</div>
							</div>

							<!-- 左の移動ボタン -->
							<a class="left carousel-control" href="#carousel-example" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
							</a>
							<!-- 右の移動ボタン -->
							<a class="right carousel-control" href="#carousel-example" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
								</a>
							</div>
						</div>

			<div class="header-search">
		      <dl class="searchbox">
		          <%= search_form_for @q,url: items_path do |f| %>
		            <dt><%= f.text_field :item_name_cont,placeholder: '商品名で検索' %></dt>
		            <dd><%= f.submit "search" , class: 'search-btn'%></dd>
		          <% end %>
		      </dl>
		    </div>
		    <br>

		    <!--商品一覧表示-->
			<div class="heading">Products　<font color="red",font size="5">2000円以上購入で送料無料！</font></div>
			<div class="col-lg-2">
				<p class="heading">Category</p>
				<% @categories.each do |c| %>
					<ul>
						<li class="tag"><%= link_to category_path(c.id) do %><%= c.name %><% end %></li><br>
					</ul>
				<% end %>
				<br>
				<p class="heading">Size</p>
				<% @sizes.each do |s| %>
					<ul>
						<li class="tag"><%= link_to size_path(s.id) do %><%= s.size_name %><% end %></li><br>
					</ul>
				<% end %>
				<br>
				<p class="heading">Brand</p>
				<% @brands.each do |b| %>
					<ul>
						<li class="tag"><%= link_to brand_path(b.id) do %><%= b.brand_name %><% end %></li><br>
					</ul>
				<% end %>
				<br>
			</div>


			<% if admin_signed_in? %>
				<%=link_to("カテゴリー編集",categories_path)%>
			<% end %><br>

					<% @items.each do |item| %>
					    <div class="item-box">
						<% if admin_signed_in? %>
						<%=link_to("編集する","/items/#{item.id}/edit")%><br>
					    <% end %>
						<!--画像画面左　登録がない場合noimageを表示-->
					    <%= link_to item_path(item.id) do %>
					    <%= attachment_image_tag item, :image, :fill, 150, 150, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %>
					<% end %>
						<!--商品内容-->
						<div class="item-text">
					    <h4><%= item.brand.brand_name %>
						<h3><%= link_to "#{item.item_name}", item_path(item) %></h3>
						<p class="tag"><%= item.category.name %></p> <p class="tag">サイズ：<%= item.size.size_name %> </p><br>
						<%= number_to_currency(item.price) %>
							<% if item.stock == 0 %>
		                      <span><font color="red">売り切れ</font></span>
			                        <% elsif item.stock >= 5 && item.stock < 20 %>
			                        <span>( 在庫：△ )</span>
				                    <% else %>
				                    <span>( 在庫：○ )</span>
				                    <% end %>
					                </div>
					            </h4>
					        </div>
					        <% end %>




    <div class="hide-box">
    <% if admin_signed_in? %>
    <center><h1>非表示アイテム一覧</h1></center>
    		<% if params[:q].present? && params[:q][:artist_name_or_label_name_or_item_name_cont].present? %>
		　　<div>
		　　<p>検索語句：　<%= params[:q][:artist_name_or_label_name_or_item_name_cont] %></p>
		　　</div>
		　　<% end %>

			<% @no_items.each do |item| %>
			    <div class="item-box">
				<% if admin_signed_in? %>
				<%=link_to("編集する","/items/#{item.id}/edit")%><br>
			    <% end %>
			<!--画像画面左　登録がない場合noimageを表示-->
			    <%= link_to item_path(item.id) do %>
			    <%= attachment_image_tag item, :image, :fill, 150, 150, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %>
			<% end %>
					<!--商品内容-->
				<div class="item-text">
			    <p><%= item.brand.brand_name %></p>
				<p><h3><%= link_to "#{item.item_name}", item_path(item) %></h3></p>
				<p class="tag"><%= item.category.name %></p> <p class="tag">サイズ：<%= item.size.size_name %></p>
				<p>¥<%= number_to_currency(item.price) %></p></div>
					<% if item.stock == 0 %>
                      <span><font color="red">売り切れ</font></span>
	                    <% elsif item.stock >= 5 && item.stock < 20 %>
	                     <span>( 在庫 : △ )</span>
		                    <% else %>
		                    <span>( 在庫 : ○ )</span>
		                    <% end %></div>
		                <% end %>
		            <% end %>
		        </div>

app/views/items/new.html.erb
<%= render 'form', item: @item %>

app/views/items/show.html.erb
　<!--　商品画像  -->
<div class="view">
  <br>
  <br>

  <% if image2_id =! nil  %>
            <!-- 任意のID指定。クラスとデータ属性の指定。 -->


                  <%= attachment_image_tag @item, :image, format: 'jpeg', class:"show_image" %>

              <!-- スライドの内容 -->
                <div class="slider">
                  <% if image2_id =! nil  %>
                    <div><%= attachment_image_tag @item, :image2, format: 'jpeg', class:"show_image" %></div>

                  <% elsif image3_id =! nil %>
                    <div><%= attachment_image_tag @item, :image3, format: 'jpeg', class:"show_image" %></div>

                  <% elsif image4_id =! nil %>
                    <div><%= attachment_image_tag @item, :image4, format: 'jpeg', class:"show_image" %></div>

                  <% elsif image5_id =! nil %>
                    <div><%= attachment_image_tag @item, :image5, format: 'jpeg', class:"show_image" %></div>
                </div>
                $('.slider').slick();


    <% else %>
    <%= attachment_image_tag @item, :image, format: 'jpeg', class:"show_image" %>
    <% end %>
    <% end %>
</div>

	<!--　商品情報　 -->
	<div class="show_text">
	<br><p class="title"><%= @item.item_name %></p>
    <span class="tag">
          <%= link_to category_path(@item.category.id) do %>
          <%= @item.category.name %>
          <% end %>
    </span>
    <span class="tag">
          <%= link_to size_path(@item.size.id) do %>
          サイズ：<%= @item.size.size_name %>
          <% end %>
    </span>
    <br>
    <br>
    	   <h2>
          価格：　<%= number_to_currency(@item.price) %><br>
        	<% if @item.stock == 0 %>
            <span><font color="red">売り切れのため、購入できません。</font></span>
            <% elsif @item.stock >= 5 && @item.stock < 20 %>
              <span>( 在庫 : △ )</span>
              <% else %>
                <span>( 在庫 : ○ )</span>
          <% end %>


        　<% if user_signed_in? %>
              <!-- 数量フォーム -->
              <%= form_for @cart do |f| %>
              数量:<%= f.number_field :count ,min:1,max:@item.stock, value:"1" %>
              <%= f.hidden_field :item_id, :value => @item.id %></h2>
            </h2>
              <%= f.submit "カートに入れる" ,class:"square_btn1"%>
          <% end %>
          <% elsif admin_signed_in? %>
              <span>残り<%= @item.stock %>個</span><br>
              <%= link_to '変更', edit_item_path(@item), class:"square_btn2" %>

           <% else %>
           <br>
           </h2>
              <font color="red">購入するには<%= link_to"ログイン",new_user_session_path %>してください。<br></font>
              　→会員登録は<%= link_to"こちら",new_user_registration_path %>
           <% end %>



          <div id="share">
          <ul>
            <!-- Facebook -->
          <div id="fb-root"></div>
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/ja_KS/sdk.js#xfbml=1&version=v2.12';
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
          <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">シェア</a></div>
          <!-- Twitter -->
          <li class="share-twitter">
            <a href="http://twitter.com/home?status=<?php echo urlencode(the_title_attribute('echo=0')); ?>%20<?php the_permalink(); ?>%20by%20" target="_blank">Twitter</a>
          </li>
          </ul>
        <br><br><br><br>
        <html>





        <!--テキスト-->
        <%= @item.description %>
         <p><h3>交換・返品ができます<br></h3>
          Sweetiepetは、着た後でも商品到着から１週間以内であれば交換・返品が出来ます。<br>

          <h3>交換について<br></h3>
          ・返品商品を当社へ返送する際の梱包料、送料等はお客様のご負担をお願いしております。<br>           
          ・新しくお渡しする商品の梱包料、送料は弊社が負担致します。<br>
           
          <h3>返品について<br></h3>
          ・返品の際の梱包料/送料はお客様のご負担となりますので予めご了承ください。<br>
          ・返金代金のお振込みにかかる手数料につきましては当社が負担いたします。<br>
          ※試着後の破れ/汚れなどによる交換・返品はお受けしておりません。<br>
          ※返品商品の当社への到着が確認でき次第、交換商品の発送、返金を行います。<br><br><br></p>
        </div>