config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'carts/index'
  get 'order' => 'admin_users#show', as: :in_order
  get 'order_end' => 'admin_users#show2', as: :order_end
  get 'order_cancel' => 'admin_users#show3', as: :order_cancel


devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  # devise_for :admins
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  get "/users/show" => "users#show",as: :users
  delete "/users/destroy" =>"users#destroy"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy]
  resources :carts
  resources :admin_users, only:[:index,:show,:destroy,:update]
  resources :orders, only: [:create,:new,:index,:update]
  resources :categories,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :brands,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :sizes,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :colors,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :contacts, only: [:index, :new, :create, :destroy]

  get "/admin_users/edit/:id" => "admin_users#edit", as: :edit_adminusers_to_users
  post "/admin_users/:id" => "admin_users#update", as: :adminusers_to_users
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :items
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name,:kana_name,:email,:phone, :message,presence: true,length: {maximum:1000}
end

app/models/detail.rb
class Detail < ApplicationRecord

	belongs_to :user
	belongs_to :item
	belongs_to :order

	enum active:{preparation: 0, shipment: 1}
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	attachment :image2
	attachment :image3
	attachment :image4
	attachment :image5
	has_many :histories
	has_many :carts
	belongs_to :category
	belongs_to :brand
	belongs_to :color
	belongs_to :size


	enum active: { display: 0, hide: 1}

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :details
	belongs_to :user

	enum order_status: { in_ordered: 0, preparation: 1, in_delivery: 2, finish: 3, cancel: 4}
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :lastname, :firstname, :postal_code, :address, :phone,:phone2,:phone3, presence: true
  validates :kana_lastname, :kana_firstname,  presence: true,
  			 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "は全角カタカナで入力して下さい"
                 }

  enum active: { active: 0, inactive: 1 }
  has_many :orders
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   def new
  	@category = Category.new
  end

  def index
  	@category = Category.new
  	@categories = Category.all
  end

  def create
  	@category = Category.new(category_params)
    @category.save
    redirect_to (categories_path)
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to (categories_path)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to (categories_path)
  end

  def show
    @items = if params[:search]
      Item.all.where("yomi_name LIKE?","%#{params[:search]}%")
      else
      Item.all
    end
    @sizes = Size.all
    @category = Category.find(params[:id])
    @categories = Category.all
    @brands = Brand.all
  end

private
	def category_params
	  params.require(:category).permit(:name)
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/categories/index.html.erb
<h1>カテゴリー</h1>
<!-- form_for部分 -->
<%= form_for @category do |f| %>
    <h2>カテゴリー追加</h2>
    <%= f.text_field :name %>
    <%= f.submit '投稿' %>
<% end %>

<h2>カテゴリー一覧</h2>
<% @categories.each do |c| %>
 <%= c.name %>
 <%= link_to "edit", edit_category_path(c) %>

  <% if c.items.presence != nil %>
    利用アイテムあり。削除不可 <br>
    <% else %>
   <%= link_to "destroy", category_path(c), method: :delete %><br>
   <% end %>

<% end %>

<br>
<%= link_to "一覧へ戻る", items_path %>　｜　<%= link_to '投稿フォームへ戻る', new_item_path %>

app/views/categories/show.html.erb
<section>
	<!--カテゴリで絞った画面-->
	<div class="view">
		<br>
		<br>
			<div class="col-lg-2">
				<p class="heading">Category</p>
				<% @categories.each do |c| %>
					<ul>
						<li class="tag"><%= link_to category_path(c.id) do %><%= c.name %><% end %></li><br>
					</ul>
				<% end %>
				<br>
				<p class="heading">Size</p>
				<% @sizes.each do |s| %>
					<ul>
						<li class="tag"><%= link_to size_path(s.id) do %><%= s.size_name %><% end %></li><br>
					</ul>
				<% end %>
				<br>
				<p class="heading">Brand</p>
				<% @brands.each do |b| %>
					<ul>
						<li class="tag"><%= link_to brand_path(b.id) do %><%= b.brand_name %><% end %></li><br>
					</ul>
				<% end %>
				<br>
			</div>


		<div class="col-lg-9">
           <div class="header-search">
		      <dl class="searchbox">
		          <%= search_form_for @q,url: items_path do |f| %>
		            <dt><%= f.text_field :item_name_cont,placeholder: '商品名で検索' %></dt>
		            <dd><%= f.submit "search" , class: 'search-btn'%></dd>
		          <% end %>
		      </dl>
		   </div>
		    <br>
			<h3 class="bold text-center">カテゴリー：<%= @category.name %> 一覧　<font color="red",font size="5">2000円以上購入で送料無料！</font></h3><br><br>

			<% if @category.items.presence == nil %>
				<div class="text-center text-color category-text-font-size">現在掲載されている商品はありません</div>
			<% end %>

			<% @items.each do |item| %>
			<% if @category.id == item.category_id %>
			    <div class="item-box">
				<!--画像画面左　登録がない場合noimageを表示-->
			    <%= link_to item_path(item.id) do %>
			    <%= attachment_image_tag item, :image, :fill, 150, 150, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %>
			    <% end %>
				<!--商品内容-->
				<div class="item-text">
			    <h4><%= item.brand.brand_name %>
				<h3><%= link_to "#{item.item_name}", item_path(item) %></h3>
				<p class="tag"><%= item.category.name %></p> <p class="tag">サイズ：<%= item.size.size_name %> </p><br>
				<%= number_to_currency(item.price) %></div>
					<% if item.stock == 0 %>
                      <span><font color="red">売り切れ</font></span>
	                        <% elsif item.stock >= 5 && item.stock < 20 %>
	                        <span>( 在庫 : △ )</span>
		                    <% else %>
		                    <span>( 在庫 : ○ )</span>
		                    <% end %>
		                </div>
		           	<% end %>
		           </h4>
		           <% end %>
		       </div>


		</div>
	</div>
</div>
</section>