config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'carts/index'
  get 'order' => 'admin_users#show', as: :in_order
  get 'order_end' => 'admin_users#show2', as: :order_end
  get 'order_cancel' => 'admin_users#show3', as: :order_cancel


devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  # devise_for :admins
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  get "/users/show" => "users#show",as: :users
  delete "/users/destroy" =>"users#destroy"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy]
  resources :carts
  resources :admin_users, only:[:index,:show,:destroy,:update]
  resources :orders, only: [:create,:new,:index,:update]
  resources :categories,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :brands,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :sizes,only: [:new, :create, :index, :update, :edit, :destroy,:show]
  resources :colors,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :contacts, only: [:index, :new, :create, :destroy]

  get "/admin_users/edit/:id" => "admin_users#edit", as: :edit_adminusers_to_users
  post "/admin_users/:id" => "admin_users#update", as: :adminusers_to_users
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :items
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name,:kana_name,:email,:phone, :message,presence: true,length: {maximum:1000}
end

app/models/detail.rb
class Detail < ApplicationRecord

	belongs_to :user
	belongs_to :item
	belongs_to :order

	enum active:{preparation: 0, shipment: 1}
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	attachment :image2
	attachment :image3
	attachment :image4
	attachment :image5
	has_many :histories
	has_many :carts
	belongs_to :category
	belongs_to :brand
	belongs_to :color
	belongs_to :size


	enum active: { display: 0, hide: 1}

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :details
	belongs_to :user

	enum order_status: { in_ordered: 0, preparation: 1, in_delivery: 2, finish: 3, cancel: 4}
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :lastname, :firstname, :postal_code, :address, :phone,:phone2,:phone3, presence: true
  validates :kana_lastname, :kana_firstname,  presence: true,
  			 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "は全角カタカナで入力して下さい"
                 }

  enum active: { active: 0, inactive: 1 }
  has_many :orders
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sweetiepet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>

      </head>
  <div class="<%= "#{@add_class}"%>-image">
   <header>
    <div class="<%= "#{@add_class}"%>-header">
      <div class="header-logo2">
        <%= link_to 'Sweetie pet',items_path %><div  class="gara">小型犬用ウェアの通販サイト</div>
        <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do" rel="stylesheet">
      </div>

      <div class="header-menu">
        <ul>
          <% if admin_signed_in? %><!--管理者がサインインした時-->
            <li><p class="gara">　<%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete %>　</p></li>
            <li><p class="gara">　<%= link_to '投稿フォーム', new_item_path %>　</p></li>
            <li><p class="gara">　<%= link_to '登録会員一覧',  admin_users_path %>　</p></li>
            <li><p class="gara">　<%= link_to 'オーダー履歴', in_order_path %>　</p></li>
            <li><p class="gara">　<%= link_to 'お問い合わせ', contacts_path %>　</p></li></ul>

            <% elsif user_signed_in? %><!--ユーザーサインイン用-->
              <li><p class="gara">　<%= link_to 'My page',users_path %>　</p></li>
            <%= link_to carts_path do %>
              <li><p class="gara">　Cart　</p></li>
              <li><p class="gara">　<%= link_to 'Contact', new_contact_path %>　</p></li>
              <% end %>

            <%= link_to destroy_user_session_path,method: :delete do %><li><p class="gara">　Logout　</p></li>
            <% end %>

            <% else %>
              <li><p class="gara">　<%= link_to 'Sign in',new_user_session_path %>　</p></li>
              <li><p class="gara">　<%= link_to 'Sign up',new_user_registration_path%>　</p></li>
              <li><p class="gara">　<%= link_to 'Contact', new_contact_path %>　</p></li>
                <div style="display: none">
                  <li><%= link_to "管理者ログイン あとで消す", new_admin_session_path %> admin@admin.com(adminadmin)</li>
                  <li><%= link_to "管理者ユーザー作成 あとで消す", new_admin_registration_path %></li>
                </div>
          <% end %>
        </ul>
   </header>
 </div>
   <div id="wrapper">
   <body>
  <div class="<%= "#{@add_class}"%>-image clearfix">
   <div class="container_all">

    <%= yield %>

   </div></div></form>
  <footer class="<%= "#{@add_class}-footer"%>">
      © 2018 Sweetiepet
  </footer>
  </html></div>
  </body></div></div></div>